# SPDX-FileCopyrightText: 2024 Jonah Brüchert <jbb@kaidan.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- name: Set up MOTIS servers
  hosts: motis
  roles:
    - motis
    - motis-proxy
    - nginx
  tasks:
    - name: Install rsync
      apt:
        name:
          - rsync
          - htop
          - zstd
