# SPDX-FileCopyrightText: 2024 Jonah Brüchert <jbb@kaidan.im>
# SPDX-License-Identifier: CC0-1.0

name: Import data

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Fetch submodules
      run: git submodule update --init --checkout --remote

    - name: Build docker images
      run: docker build -t transitous . -f ci/container/Containerfile

    - name: Restore cached feeds
      uses: actions/cache/restore@v4
      with:
        path: |
          downloads/
          out/*.zip
        key: feeds
        restore-keys: |
          feeds

    - name: Fetch GTFS-Feeds
      run: |
        docker run -v $PWD:/transitous -w /transitous transitous ci/fetch-feeds.py timer
        docker run -v $PWD:/transitous -w /transitous transitous src/generate-attribution.py

    - name: Import Feeds into motis
      run: |
        docker run -v $PWD:/transitous -w /transitous transitous src/generate-motis-config.py import
        docker run -v $PWD:/transitous -w /transitous/out transitous ../ci/motis-import.py
        docker run -v $PWD:/transitous -w /transitous transitous src/generate-motis-config.py full

    - name: Cache feeds
      uses: actions/cache/save@v4
      with:
        path: |
          downloads/
          out/*.zip
        key: feeds-${{ hashFiles('downloads/*') }}

    - name: Compress results
      run: |
        tar -C out/ --zstd -cf feeds.tar.zst .

    - name: Upload results
      run: curl --upload-file feeds.tar.zst https://transfer.sh/feeds.tar.zst
